# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W3Swb1jW7W0Ls8z9ZtPrPmouVQYLvXS1
"""

import tensorflow as tf
import keras
import numpy as np


sentences = ['pokaz kase', 'stan konta', 'pokaz pieniadze', 'chce wplacic', 'doloze', 'wplacam', 'zabieram', 'daj pieniadze', 'wyplacam']
labels = [0,0,0,1,1,1,2,2,2]

tokenizer = tf.keras.preprocessing.text.Tokenizer()

tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)
paddes = keras.preprocessing.sequence.pad_sequences(sequences)

model = tf.keras.Sequential([
    keras.layers.Embedding(input_dim=100, output_dim=8),
    keras.layers.GlobalAveragePooling1D(),
    keras.layers.Dense(8, activation='relu'),
    keras.layers.Dense(3, activation='softmax')
])

model.compile(
    optimizer = 'adam',
    loss = 'sparse_categorical_crossentropy',
    metrics=['accuracy']
)


paddes = np.array(paddes)
labels = np.array(labels)

model.fit(paddes, labels, epochs = 500, verbose = 0)

def get_intend(user_text):
    seq = tokenizer.texts_to_sequences([user_text])
    pad_seq = keras.preprocessing.sequence.pad_sequences(seq, maxlen=paddes.shape[1])


    prediction = model.predict(pad_seq)
    model.save('model_banku_AI.h5')
    print('Model został poprawnie zapisany!')
    return np.argmax(prediction)

saldo = 1000

print ("Witaj w banku AI")

while True:
    zdanie = input("Napisz proszę, co chciałbyś zrobić (po wpisaniu koniec, program zakonczy dzialanie).")

    if zdanie.lower() == 'koniec':
        break

    intencja = get_intend(zdanie)

    if intencja == 0:
        print(f" Saldo konta wynosi {saldo} zł")
    elif intencja == 1:
        kwota = int(input("Ile wpłacamy?"))
        saldo += kwota
        print (f"Aktualne saldo wynosi {saldo}")
    elif intencja == 2:
        kwota = int(input('Ile chciałbyś wypłacić z konta?'))
        if kwota > saldo:
            print(f'Brak mozliwosci wyplacenia {kwota}, nie posiadasz tylu srodkow na koncie. Stan konta: {saldo}')
        else:
            saldo -= kwota
            print (f'Pieniądze zostały wypłacone, stan konta po wypłacie wynosi: {saldo}')